# Automatically generated by configure - do not modify
SRC_PATH=/home/xubo/fuzzers/FirmAFL/qemu_mode/DECAF_qemu_2.10/roms/seabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
